# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: controller-app
spec:
  selector:
    app: controller-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
